# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips_app', '0003_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='Plan',
            new_name='plan',
        ),
    ]
