# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-14 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='Network',
        ),
        migrations.AddField(
            model_name='shows',
            name='network',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-10-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
