# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-12 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20191111_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_app.Book'),
        ),
    ]
