# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0003_delete_jobmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employee',
            new_name='user',
        ),
    ]
