# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trips',
            new_name='planner',
        ),
    ]
